### PR TITLE
Add OWN logo

### PR DESCRIPTION
**Pull request by kojiadrianojr**
image
image

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Iconic!

**Review by swengr-janan — APPROVED** [review]
AGITH

**Comment by swengr-janan** [comment]
ARGHHHHHHHHHHH HAHAHAH

**Comment by harveyjavier** [comment]
HAHAHAHA

**Comment by harveyjavier** [comment]
Sorry balpz part two!

**Comment by swengr-janan** [comment]
Hahaha bawi sa sunod 😆

**Pull request merged**
