### PR TITLE
Navigation bar update!

### PR DESCRIPTION
**Pull request by kojiadrianojr**
✅Add link to twitter 
image
✅Fix mobile view, Added a button to toggle menu
image
image

### CODE REVIEW

**Comment by harveyjavier** [comment]
Screenshot 2021-05-31 152834

Tolpu talaga an? or hanggang jan nlng limit ng bounds nya? haha

**Comment by kojiadrianojr** [comment]
> Screenshot 2021-05-31 152834
> 
> Tolpu talaga an? or hanggang jan nlng limit ng bounds nya? haha

ay hindi po hehehe kita rin po ung other side nung square

**Review by swengr-janan — APPROVED** [review]
Link added

**Comment by harveyjavier** [comment]
ahh oks haha

**Comment by kojiadrianojr** [comment]
image

kaso mas marami su space sa left

**Review by harveyjavier — APPROVED** [review]
Responsive!

**Pull request merged**
