### PR TITLE
Refactor token logo loader 

### PR DESCRIPTION
**Pull request by kojiadrianojr**
References issue #41

Replace the patch solution created earlier to load the token logos
- Created a token list for tokens missing on trustwallet repo 
- Dynamic token loader

Before: 
image

After:
image

### CODE REVIEW

**Review by mativanarquero — APPROVED** [review]
Refactored!

**Review by kbaldo — APPROVED** [review]
Great!

**Review by swengr-janan — APPROVED** [review]
AGITH

**Comment by kojiadrianojr** [comment]
Closes issue #41

**Pull request merged**
