### PR TITLE
Kclp token

### PR DESCRIPTION
**Pull request by kojiadrianojr**
image

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
Added!

**Review by kbaldo — APPROVED** [review]
Added-ed!

**Comment by harveyjavier** [comment]
Follow pa rin natin @kojiadrianojr next time kahit sa PR yung right naming convention sa commits. Present verb tense nauuna sa sentence. Sample in your case, `Add KCLP Token`. Anyways, apprubing

**Review by harveyjavier — APPROVED** [review]
KCLP-fied!

**Pull request merged**
